FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    streamlit \
    pandas \
    plotly \
    requests \
    psycopg2-binary

COPY streamlit/ /app/

EXPOSE 8501

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]